language: rust
rust:
    - nightly
    - beta
    - stable

before_script:
    - rustc -V
    - cargo -V
    - if [[ "$TRAVIS_RUST_VERSION" != "nightly" ]]; then rustup component add clippy; fi

script:
    - if [[ "$TRAVIS_RUST_VERSION" != "nightly" ]]; then cargo clippy; fi

notifications:
    email: false
